name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}-linting"
  cancel-in-progress: true

jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: pnpm

      - name: Handle vitest cache
        id: vitest-cache
        uses: actions/cache@v3
        env:
          cache-name: vitest
          cache-fingerprint: ${{ hashFiles('**/node_mdoules/.cache/.vitest') }}
        with:
          path: "**/node_mdoules/.cache/.vitest"
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}

      - name: Install dependencies
        run: pnpm install

      - name: Unit Tests
        run: pnpm run test

      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.3

